name: dartstruct_generator
description: dartstruct generator is an annotation processor generator using source_gen and inspired by Java MapStruct.
version: 0.0.0

environment:
  sdk: ^3.0.0

dependencies:
  dartstruct:
    path: ../core
  analyzer: <6.0.0
  build: ^2.4.1
  code_builder: ^4.10.0
  dart_style: <2.3.8
  equatable: ^2.0.5
  logging: ^1.2.0
  recase: ^4.1.0
  source_gen: ^1.5.0


dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
