name: dartstruct
description: dartstruct is an annotation processor generator using source_gen and inspired by Java MapStruct.
version: 0.0.0

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.15.0
  path: ^1.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
